# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Review.delete_all
Movie.delete_all
User.delete_all

movies = [
    {title: "Gladiator", year: "2000", starring: " Russell Crowe, Joaquin Phoenix", tag_line: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", link: "https://www.imdb.com/title/tt0172495/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "A Beautiful Mind", year: "2001", starring: " Russell Crowe, Ed Harris", tag_line: "After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.", link: "https://www.imdb.com/title/tt0268978/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BMzcwYWFkYzktZjAzNC00OGY1LWI4YTgtNzc5MzVjMDVmNjY0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "Chicago", year: "2002", starring: "Renée Zellweger, Catherine Zeta-Jones", tag_line: "Two death-row murderesses develop a fierce rivalry while competing for publicity, celebrity, and a sleazy lawyer's attention.", link: "https://www.imdb.com/title/tt0299658/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BN2E3NDU1ZTktNzZjNy00MWU3LWI4YmMtMjdjNTIzMDU0MDdiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY209_CR1,0,140,209_AL_.jpg"},
    {title: "The Lord of the Rings: The Return of the King", year: "2003", starring: " Elijah Wood, Viggo Mortensen", tag_line: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", link: "https://www.imdb.com/title/tt0167260/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "Million Dollar Baby", year: "2004", starring: " Hilary Swank, Clint Eastwood", tag_line: "A determined woman works with a hardened boxing trainer to become a professiona", link: "https://www.imdb.com/title/tt0405159/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BMTkxNzA1NDQxOV5BMl5BanBnXkFtZTcwNTkyMTIzMw@@._V1_UY209_CR1,0,140,209_AL_.jpg"},
    {title: "Crash", year: "2005", starring: " Don Cheadle, Sandra Bullock", tag_line: "Los Angeles citizens with vastly separate lives collide in interweaving stories of race, loss and redemption.", link: "https://www.imdb.com/title/tt0375679/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BOTk1OTA1MjIyNV5BMl5BanBnXkFtZTcwODQxMTkyMQ@@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "The Departed", year: "2006", starring: " Leonardo DiCaprio, Matt Damon", tag_line: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.", link: "https://www.imdb.com/title/tt0407887/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "No Country for Old Men", year: "2007", starring: " Tommy Lee Jones, Javier Bardem", tag_line: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.", link: "https://www.imdb.com/title/tt0477348/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_UY209_CR1,0,140,209_AL_.jpg"},
    {title: "Slumdog Millionaire", year: "2008", starring: " Dev Patel, Freida Pinto", tag_line: "A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of \"Who Wants to be a Millionaire?\".", link: "https://www.imdb.com/title/tt1010048/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BZmNjZWI3NzktYWI1Mi00OTAyLWJkNTYtMzUwYTFlZDA0Y2UwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "The Hurt Locker", year: "2009", starring: " Jeremy Renner, Anthony Mackie", tag_line: "During the Iraq War, a Sergeant recently assigned to an army bomb squad is put at odds with his squad mates due to his maverick way of handling his work.", link: "https://www.imdb.com/title/tt0887912/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BYWYxZjU2MmQtMmMzYi00ZWUwLTg2ZWQtMDExZTVlYjM3ZWM1XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX140_CR0,0,140,209_AL_.jpg"},
    {title: "The Kings Speach", year: "2010", starring: " Colin Firth, Geoffrey Rush", tag_line: "The story of King George VI, his impromptu ascension to the throne of the British Empire in 1936, and the speech therapist who helped the unsure monarch overcome his stammer.", link: "https://www.imdb.com/title/tt1504320/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BMzU5MjEwMTg2Nl5BMl5BanBnXkFtZTcwNzM3MTYxNA@@._V1_UY209_CR1,0,140,209_AL_.jpg"},
    {title: "The Artist", year: "2011", starring: " Jean Dujardin, Bérénice Bejo", tag_line: "An egomaniacal film star develops a relationship with a young dancer against the backdrop of Hollywood's silent era.", link: "https://www.imdb.com/title/tt1655442/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BMDUyZWU5N2UtOWFlMy00MTI0LTk0ZDYtMzFhNjljODBhZDA5XkEyXkFqcGdeQXVyNzA4ODc3ODU@._V1_UY209_CR3,0,140,209_AL_.jpg"},
    {title: "Argo", year: "2012", starring: " Ben Affleck, Bryan Cranston", tag_line: "Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1979.", link: "https://www.imdb.com/title/tt1024648/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BNzljNjY3MDYtYzc0Ni00YjU0LWIyNDUtNTE0ZDRiMGExMjZlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "12 Years a Slave", year: "2013", starring: " Chiwetel Ejiofor, Michael Kenneth Williams", tag_line: "In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.", link: "https://www.imdb.com/title/tt2024544/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "Birdman or (The Unexpected Virtue of Ignorance", year: "2014", starring: " Michael Keaton, Zach Galifianakis", tag_line: "A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.", link: "https://www.imdb.com/title/tt2562232/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BODAzNDMxMzAxOV5BMl5BanBnXkFtZTgwMDMxMjA4MjE@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "Spotlight", year: "2015", starring: " Mark Ruffalo, Michael Keaton,", tag_line: "The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese, shaking the entire Catholic Church to its core.", link: "https://www.imdb.com/title/tt1895587/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BMjIyOTM5OTIzNV5BMl5BanBnXkFtZTgwMDkzODE2NjE@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "Moonlight", year: "2016", starring: "Mahershala Ali, Naomie Harris", tag_line: "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.", link: "https://www.imdb.com/title/tt4975722/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "The Shape of Water", year: "2017", starring: "Sally Hawkins, Octavia Spencer,", tag_line: "At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.", link: "https://www.imdb.com/title/tt5580390/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BNGNiNWQ5M2MtNGI0OC00MDA2LWI5NzEtMmZiYjVjMDEyOWYzXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_UY209_CR0,0,140,209_AL_.jpg"},
    {title: "Green Book", year: "2018", starring: " Viggo Mortensen, Mahershala Ali", tag_line: "A working-class Italian-American bouncer becomes the driver of an African-American classical pianist on a tour of venues through the 1960s American South.", link: "https://www.imdb.com/title/tt6966692/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BYzIzYmJlYTYtNGNiYy00N2EwLTk4ZjItMGYyZTJiOTVkM2RlXkEyXkFqcGdeQXVyODY1NDk1NjE@._V1_UX140_CR0,0,140,209_AL_.jpg"},
    {title: "Parasite", year: "2019", starring: "Kang-ho Song, Sun-kyun Lee", tag_line: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", link: "https://www.imdb.com/title/tt6751668/?ref_=ttls_li_tt", image: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UY209_CR0,0,140,209_AL_.jpg"},
]

movies.each do |movie|
    Movie.create(movie)
end